type T = { zh: string; en: string; it: string; es: string };

// ── Nav ──
export const nav = {
  overview: { zh: `前言`, en: `Preamble`, it: `Premessa`, es: `Preámbulo` } as T,
  highlights: { zh: `亮点`, en: `Highlights`, it: `Punti salienti`, es: `Destacados` } as T,
  guide: { zh: `游览指南`, en: `Guide`, it: `Guida`, es: `Guía` } as T,
  transport: { zh: `交通`, en: `Transport`, it: `Trasporti`, es: `Transporte` } as T,
  reviews: { zh: `评价`, en: `Reviews`, it: `Recensioni`, es: `Opiniones` } as T,
  encyclopedia: { zh: `百科`, en: `Encyclopedia`, it: `Enciclopedia`, es: `Enciclopedia` } as T,
  ecology: { zh: `生态`, en: `Ecology`, it: `Ecologia`, es: `Ecología` } as T,
  gallery: { zh: `图集`, en: `Gallery`, it: `Galleria`, es: `Galería` } as T,
  faq: { zh: `问答`, en: `FAQ`, it: `Domande`, es: `Preguntas` } as T,
  support: { zh: `支持我们`, en: `Support Us`, it: `Sostienici`, es: `Apóyanos` } as T,
};

export const viewMode = {
  tourist: { zh: `游客模式`, en: `Traveler`, it: `Viaggiatore`, es: `Viajero` } as T,
  science: { zh: `科普模式`, en: `Field Notes`, it: `Note sul campo`, es: `Notas de campo` } as T,
} as const;

// ── Hero ──
export const hero = {
  breadcrumb: {
    zh: `阿根廷自然保护区 ＞ 科尔多瓦省 ＞ 卡拉穆奇塔山谷 ＞ La Olla 水潭`,
    en: `Argentine Nature Reserve › Córdoba Province › Calamuchita Valley › La Olla Pool`,
    it: `Riserva Naturale Argentina › Provincia di Córdoba › Valle di Calamuchita › Poza La Olla`,
    es: `Reserva Natural Argentina › Provincia de Córdoba › Valle de Calamuchita › Poza La Olla`,
  } as T,
  title: {
    zh: `La Olla ·<br/><span class="italic text-[color:var(--color-sun)]">卡拉穆奇塔山谷的天然水潭</span>`,
    en: `La Olla ·<br/><span class="italic text-[color:var(--color-sun)]">a natural pool in Calamuchita</span>`,
    it: `La Olla ·<br/><span class="italic text-[color:var(--color-sun)]">una pozza naturale a Calamuchita</span>`,
    es: `La Olla en La Cumbrecita, Córdoba`,
  } as T,
  subtitle: {
    zh: `La Olla · 科尔多瓦省卡拉穆奇塔山谷中，一处被瀑布冲刷千年、深约 6 米的天然圆形水潭。紧邻步行小镇拉昆布雷西塔，是阿根廷中部最治愈的远足与夏日戏水秘境。`,
    en: `La Olla · A circular natural pool about 6 m deep, carved by a waterfall over millennia in the Calamuchita Valley of Córdoba. Next to the pedestrian town of La Cumbrecita, it is one of the most soothing hiking and summer-swimming spots in central Argentina.`,
    it: `La Olla · Una pozza naturale circolare di circa 6 m di profondità, scolpita da una cascata nel corso dei millenni nella valle di Calamuchita, a Córdoba. Accanto al paese pedonale di La Cumbrecita, è uno dei luoghi più rigeneranti per escursioni e bagni estivi nell'Argentina centrale.`,
    es: `La Olla · Una poza natural circular de unos 6 m de profundidad, tallada por una cascada a lo largo de milenios en el Valle de Calamuchita, Córdoba. Junto al pueblo peatonal de La Cumbrecita, es uno de los rincones más relajantes para caminatas y baños de verano del centro de Argentina.`,
  } as T,
  viewMap: { zh: `在 Google 地图上查看位置`, en: `View location on Google Maps`, it: `Vedi la posizione su Google Maps`, es: `Ver la ubicación en Google Maps` } as T,
  statReviews: { zh: `评价`, en: `reviews`, it: `recensioni`, es: `opiniones` } as T,
  statLength: { zh: `评分`, en: `Rating`, it: `Valutazione`, es: `Puntuación` } as T,
  statFalls: { zh: `类型`, en: `Type`, it: `Tipo`, es: `Tipo` } as T,
  statFlow: { zh: `所在地`, en: `Location`, it: `Località`, es: `Ubicación` } as T,
  poetic: {
    zh: `一潭碧水，<br/><span class="text-[color:var(--color-sun)]">半座山谷的回声</span>`,
    en: `One still pool.<br/><span class="text-[color:var(--color-sun)]">Half a valley's echo.</span>`,
    it: `Una pozza ferma.<br/><span class="text-[color:var(--color-sun)]">L'eco di mezza valle.</span>`,
    es: `Una poza en calma.<br/><span class="text-[color:var(--color-sun)]">El eco de medio valle.</span>`,
  } as T,
  chip1: { zh: `免费开放`, en: `Free access`, it: `Accesso libero`, es: `Acceso libre` } as T,
  chip2: { zh: `约 6 米深`, en: `~6 m deep`, it: `~6 m di profondità`, es: `~6 m de profundidad` } as T,
  chip3: { zh: `远足区`, en: `Hiking area`, it: `Zona di escursioni`, es: `Zona de senderismo` } as T,
  tags: {
    zh: [`天然水潭`, `瀑布壶穴`, `拉昆布雷西塔`, `夏日戏水`],
    en: [`Natural pool`, `Waterfall pothole`, `La Cumbrecita`, `Summer swim`],
    it: [`Pozza naturale`, `Marmitta della cascata`, `La Cumbrecita`, `Bagni estivi`],
    es: [`Poza natural`, `Marmita de cascada`, `La Cumbrecita`, `Baños de verano`],
  } as T,
};

// ── Manifesto ──
export const manifesto = {
  sectionNum: { zh: `前言`, en: `Preamble`, it: `Premessa`, es: `Preámbulo` } as T,
  heading: {
    zh: `一潭碧水，<br/><em class="text-[color:var(--color-emerald)]">半座山谷的回声</em>`,
    en: `One still pool.<br/><em class="text-[color:var(--color-emerald)]">Half a valley's echo.</em>`,
    it: `Una pozza ferma.<br/><em class="text-[color:var(--color-emerald)]">L'eco di mezza valle.</em>`,
    es: `Una poza en calma.<br/><em class="text-[color:var(--color-emerald)]">El eco de medio valle.</em>`,
  } as T,
  subheading: { zh: `致每一位走进卡拉穆奇塔的旅人`, en: `To every traveller who walks into Calamuchita`, it: `A ogni viaggiatore che entra a Calamuchita`, es: `A todo viajero que entra a Calamuchita` } as T,
  p1: {
    zh: `欢迎来到 La Olla。在阿根廷科尔多瓦省的卡拉穆奇塔山谷，拉昆布雷西塔这座没有汽车的步行小镇旁，瀑布用千万年的时间，把一块坚硬的花岗岩冲刷成了一个深约 6 米、蓝得发亮的天然水潭。这里没有门票，也没有围栏，只有水、岩与风。`,
    en: `Welcome to La Olla. In the Calamuchita Valley of Córdoba, Argentina, beside the car-free pedestrian town of La Cumbrecita, a waterfall spent millions of years hollowing a hard granite boulder into a turquoise natural pool about 6 m deep. There is no ticket and no fence — only water, rock and wind.`,
    it: `Benvenuti a La Olla. Nella valle di Calamuchita, a Córdoba, accanto al paese pedonale di La Cumbrecita, una cascata ha impiegato milioni di anni per scavare un masso di granito fino a formare una pozza naturale turchese di circa 6 m di profondità. Nessun biglietto, nessuna recinzione: solo acqua, roccia e vento.`,
    es: `Bienvenido a La Olla. En el Valle de Calamuchita, Córdoba, junto al pueblo peatonal sin autos de La Cumbrecita, una cascada tardó millones de años en ahuecar un bloque de granito hasta formar una poza natural turquesa de unos 6 m de profundidad. No hay entrada ni cerco: solo agua, roca y viento.`,
  } as T,
  p2: {
    zh: `这里没有游乐设施，没有喧嚣——只有瀑布落入壶穴的轰鸣、岩壁间折射的绿光，以及夏日里跃入清凉池水的笑声。清晨，山谷常被薄雾笼罩；正午，阳光把水面照得剔透；而雨后，瀑布水量最盛，是整段步道最动听的几分钟。`,
    en: `There are no rides, no noise — only the roar of the falls dropping into the pothole, the green light refracting off the rock, and the laughter of those who leap into the cool water in summer. At dawn the valley often wears a thin mist; at noon the sun makes the surface crystalline; after rain the waterfall swells to its most moving few minutes.`,
    it: `Non ci sono giostre né rumori — solo il fragore della cascata che cade nella marmitta, la luce verde che si rifrange sulla roccia e le risa di chi si tuffa nell'acqua fresca d'estate. All'alba la valle spesso ha una nebbia tenue; a mezzogiorno il sole rende la superficie cristallina; dopo la pioggia la cascata è al suo massimo, i minuti più toccanti del sentiero.`,
    es: `No hay juegos ni ruido — solo el rugido de la cascada cayendo en la marmita, la luz verde que se refracta en la roca y las risas de quienes se lanzan al agua fresca en verano. Al amanecer la valle suele vestir una neblina tenue; al mediodía el sol vuelve la superficie cristalina; tras la lluvia la cascata crece hasta sus minutos más conmovedores.`,
  } as T,
  p3: {
    zh: `作为一个独立的旅行与自然向导团队，我们搭建本网站，不仅为了告诉你如何抵达这处水潭，更想邀请你以“守护者”而非“游客”的身份来到这里。当你站在被水流打磨了千万年的岩边，你既是这片山谷的见证者，也是它得以长存的共谋者。`,
    en: `As an independent travel and nature guide, we built this site not only to tell you how to reach the pool, but to invite you to arrive as a guardian rather than a mere visitor. When you stand on the rock shaped by water for millions of years, you become both a witness to this valley and a co-keeper of its future.`,
    it: `Come guida indipendente di viaggio e natura, abbiamo creato questo sito non solo per spiegarti come arrivare, ma per invitarti a venire come custode e non solo come visitatore. Sulla roccia modellata dall'acqua da milioni di anni, diventi testimone della valle e suo co-custode.`,
    es: `Como guía independiente de viaje y naturaleza, creamos este sitio no solo para decirte cómo llegar, sino para invitarte a venir como guardián y no solo como visitante. Cuando te paras en la roca modelada por el agua durante millones de años, te vuelves testigo del valle y co-custodio de su futuro.`,
  } as T,
  p4: {
    zh: `🌿 <strong>守护公共的自然风景。</strong>La Olla 与拉昆布雷西塔所在的卡拉穆奇塔山谷，是科尔多瓦省最受珍视的生态旅游区之一。作为独立的教育项目，本网站的初衷正与此契合：La Olla 不仅属于每一位旅人，更是这片自然遗产的重要一环。我们呼吁每一位访客以“无痕山林（Leave No Trace）”的方式到访，助力山谷生态的永续。`,
    en: `🌿 <strong>Guardians of a shared natural landscape.</strong> La Olla and the Calamuchita Valley around La Cumbrecita are among Córdoba's most cherished ecotourism areas. As an independent educational project, this site shares that purpose: La Olla belongs to every traveller and is a vital part of this natural heritage. We invite every visitor to come by the "Leave No Trace" ethic.`,
    it: `🌿 <strong>Custodi di un paesaggio naturale condiviso.</strong> La Olla e la valle di Calamuchita attorno a La Cumbrecita sono tra le aree ecoturistiche più amate di Córdoba. Come progetto educativo indipendente, il sito condivide quello scopo: La Olla appartiene a ogni viaggiatore ed è parte vitale di questo patrimonio. Invitiamo ognuno a venire con l'etica del "Non Lasciare Traccia".`,
    es: `🌿 <strong>Custodios de un paisaje natural compartido.</strong> La Olla y el Valle de Calamuchita en torno a La Cumbrecita son una de las zonas ecoturísticas más queridas de Córdoba. Como proyecto educativo independiente, este sitio comparte ese propósito: La Olla pertenece a cada viajero y es parte vital de este patrimonio natural. Invitamos a cada visitante a venir bajo la ética de "No Dejar Rastro".`,
  } as T,
  closing: {
    zh: `带走一张水光潋滟的照片，留下岩壁本来的样子。<br/>让这潭山谷的碧水，为每个夏天依旧清澈。`,
    en: `Take a photo of the shimmering water. Leave the rock as you found it.<br/>Let this valley pool stay clear for every summer.`,
    it: `Porta via una foto dell'acqua scintillante. Lascia la roccia come l'hai trovata.<br/>Che questa pozza della valle resti limpida per ogni estate.`,
    es: `Lleva una foto del agua centelleante. Deja la roca como la encontraste.<br/>Que esta poza del valle siga clara para cada verano.`,
  } as T,
  chip1: { zh: `瀑布水潭`, en: `Waterfall pool`, it: `Pozza della cascata`, es: `Poza de cascada` } as T,
  chip2: { zh: `步行小镇`, en: `Pedestrian town`, it: `Paese pedonale`, es: `Pueblo peatonal` } as T,
  chip3: { zh: `卡拉穆奇塔`, en: `Calamuchita`, it: `Calamuchita`, es: `Calamuchita` } as T,
  chip4: { zh: `科尔多瓦 · 阿根廷`, en: `Córdoba · Argentina`, it: `Córdoba · Argentina`, es: `Córdoba · Argentina` } as T,
};

// ── Highlights ──
export const highlights = {
  sectionNum: { zh: `游览亮点`, en: `Highlights`, it: `Punti salienti`, es: `Destacados` } as T,
  heading: { zh: `三种<em class="text-[color:var(--color-sun)]">体验</em>`, en: `Three ways<br/><em class="text-[color:var(--color-sun)]">to feel it</em>`, it: `Tre modi<br/><em class="text-[color:var(--color-sun)]">di sentirlo</em>`, es: `Tres formas<br/><em class="text-[color:var(--color-sun)]">de sentirlo</em>` } as T,
  items: [
    { icon: '💧', num: '01', title: { zh: `碧绿的天然水潭`, en: `The turquoise pool`, it: `La pozza turchese`, es: `La poza turquesa` } as T, desc: { zh: `瀑布千万年冲刷花岗岩，雕出一口深约 6 米、近乎正圆的天然水潭，水质清澈见底，在岩壁间泛着翡翠般的绿光。`, en: `A waterfall carved the granite for millions of years into a near-perfect circular pool about 6 m deep, with water so clear it glows emerald green between the rocks.`, it: `Una cascata ha scolpito il granito per milioni di anni in una pozza quasi circolare di circa 6 m di profondità, con un'acqua così limpida da brillare verde smeraldo tra le rocce.`, es: `Una cascada talló el granito durante millones de años hasta formar una poza casi circular de unos 6 m de profundidad, con un agua tan clara que brilla verde esmeralda entre las rocas.` } as T, img: '/gallery/la-olla-1.jpg' },
    { icon: '🌊', num: '02', title: { zh: `瀑布与壶穴`, en: `Waterfall & pothole`, it: `Cascata e marmitta`, es: `Cascada y marmita` } as T, desc: { zh: `上方溪水倾泻而下，年复一年地打磨出这口“锅状”壶穴（marmita）。水量随季节变化，雨后尤为壮观，是整段步道最动听的乐章。`, en: `A stream plunges from above, polishing this "pot-shaped" pothole (marmita) year after year. The flow changes with the seasons and is most spectacular after rain — the most moving passage of the trail.`, it: `Un ruscello si getta dall'alto, levigando anno dopo anno questa "marmitta" a forma di pentola. La portata cambia con le stagioni ed è spettacolare dopo la pioggia: il tratto più toccante del sentiero.`, es: `Un arroyo cae desde arriba, puliendo año tras año esta "marmita" en forma de olla. El caudal cambia con las estaciones y es espectacular tras la lluvia: el tramo más conmovedor del sendero.` } as T, img: '/gallery/la-olla-2.jpg' },
    { icon: '🥾', num: '03', title: { zh: `远足与戏水`, en: `Hike & swim`, it: `Trekking e bagno`, es: `Caminata y baño` } as T, desc: { zh: `从步行小镇拉昆布雷西塔出发，沿标识步道徒步约 1–2 小时即可抵达；夏季可跃入清凉池水，是科尔多瓦家庭最爱的避暑戏水地之一。`, en: `From the pedestrian town of La Cumbrecita, a signed trail reaches the pool in about 1–2 hours; in summer you can leap into the cool water — one of Córdoba families' favourite places to beat the heat.`, it: `Dal paese pedonale di La Cumbrecita, un sentiero segnalato raggiunge la pozza in circa 1–2 ore; d'estate ci si può tuffare nell'acqua fresca — uno dei luoghi preferiti dalle famiglie di Córdoba per sfuggire al caldo.`, es: `Desde el pueblo peatonal de La Cumbrecita, un sendero señalizado llega a la poza en unas 1–2 horas; en verano puedes lanzarte al agua fresca: uno de los lugares favoritos de las familias de Córdoba para escapar del calor.` } as T, img: '/gallery/la-olla-3.jpg' },
  ],
};

// ── Practical Info ──
export const practical = {
  sectionNum: { zh: `实用游览指南`, en: `Practical Guide`, it: `Guida pratica`, es: `Guía práctica` } as T,
  heading: { zh: `出发前<em class="text-[color:var(--color-emerald)]">必读</em>`, en: `Read this<br/><em class="text-[color:var(--color-emerald)]"> before you go</em>.`, it: `Leggi questo<br/><em class="text-[color:var(--color-emerald)]">prima di partire</em>.`, es: `Lee esto<br/><em class="text-[color:var(--color-emerald)]"> antes de ir</em>.` } as T,
  safetyTitle: { zh: `出行前的安全提醒`, en: `Before-you-go safety notes`, it: `Note di sicurezza prima di partire`, es: `Avisos de seguridad antes de ir` } as T,
  signal: { zh: `步道及水潭区域无移动网络覆盖，请在镇中心提前加载好地图，并向家人报备行程。`, en: `The trail and pool area have no mobile coverage — load your map in town first and tell family your plan.`, it: `Sentiero e pozza non hanno campo: carica la mappa in paese e avvisa i tuoi.`, es: `El sendero y la poza no tienen cobertura móvil: carga el mapa en el pueblo y avisa a tu familia.` } as T,
  accessibility: { zh: `步道含土路与需攀爬的石阶，不适合轮椅与婴儿推车；携带婴幼儿的家庭建议使用背带。`, en: `The trail has dirt paths and stone steps to climb — not suitable for wheelchairs or strollers; bring a baby carrier for infants.`, it: `Il sentiero ha terra e scalini di pietra: non adatto a carrozzine; porta un marsupio per i neonati.`, es: `El sendero tiene tierra y escalones de piedra: no apto para sillas de ruedas ni coches; usa un portabebés.` } as T,
  cards: [
    { icon: '🗓️', label: { zh: `最佳季节`, en: `Best season`, it: `Stagione ideale`, es: `Mejor época` } as T, value: { zh: `10–3 月`, en: `Oct–Mar`, it: `ott–mar`, es: `oct–mar` } as T, desc: { zh: `春夏季（10 月至次年 3 月）水量充沛、适合戏水，是最佳到访期；冬季水凉、步道湿滑，仍可徒步观景。白天前往、趁着天黑前返回最安心。`, en: `Spring and summer (Oct–Mar) bring full water and swimming — the best time to visit. In winter the water is cold and the trail slippery, though still hikeable. Go in daylight and return before dark.`, it: `Primavera ed estate (ott–mar) regalano acqua abbondante e possibilità di bagno: il momento migliore. In inverno l'acqua è fredda e il sentiero scivoloso, ma si può comunque camminare. Vai di giorno e torna prima del buio.`, es: `Primavera y verano (oct–mar) traen agua abundante y baños: la mejor época. En invierno el agua está fría y el sendero resbaloso, aunque se puede caminar. Ve de día y regresa antes de oscurecer.` } as T },
    { icon: '🎟️', label: { zh: `门票与费用`, en: `Ticket & cost`, it: `Ingresso e costo`, es: `Entrada y costo` } as T, value: { zh: `免费`, en: `Free`, it: `Accesso libero`, es: `Acceso libre` } as T, desc: { zh: `La Olla 是免费开放的天然区域，没有任何售票亭或闸口，徒步即可抵达。请把它当作大家共同的风景来珍惜。`, en: `La Olla is a free natural area with no booth or gate — you simply walk in. Please treat it as a landscape we all share.`, it: `La Olla è un'area naturale gratuita, senza biglietteria né cancelletti: ci si arriva a piedi. Trattala come un paesaggio di tutti.`, es: `La Olla es un área natural gratuita, sin boletería ni cerco: se llega caminando. Por favor, trátela como un paisaje de todos.` } as T },
    { icon: '⏱️', label: { zh: `游览时长`, en: `Duration`, it: `Durata`, es: `Duración` } as T, value: '2–4 h', desc: { zh: `从拉昆布雷西塔镇中心往返徒步约 1–2 小时，加上在潭边戏水、拍照与休息，半天即可轻松完成。若连同小镇与周边步道，可安排一整天。`, en: `The round-trip walk from La Cumbrecita centre is about 1–2 hours; add swimming, photos and rest and a half-day is comfortable. Pair it with the town and nearby trails for a full day.`, it: `L'andata e ritorno dal centro di La Cumbrecita è di circa 1–2 ore; con bagno, foto e soste, mezza giornata è comoda. Unita al paese e ai sentieri vicini, diventa una giornata intera.`, es: `La ida y vuelta desde el centro de La Cumbrecita son unas 1–2 horas; sumando baño, fotos y descanso, media jornada es cómoda. Sumando el pueblo y los senderos cercanos, completa un día entero.` } as T },
    { icon: '', label: { zh: `到访须知`, en: `Visit notes`, it: `Note di visita`, es: `Notas de visita` } as T, value: '', desc: '', tips: [{ zh: `岩壁与池边<strong>湿滑无比</strong>，请穿防滑鞋、与边缘保持距离，切勿跳水`, en: `The rock and pool edge are <strong>extremely slippery</strong> — wear grippy shoes, keep clear of the edge and never dive`, it: `La roccia e il bordo della pozza sono <strong>molto scivolosi</strong>: indossa scarpe antiscivolo, resta lontano dal bordo e non tuffarti`, es: `La roca y el borde de la poza están <strong>muy resbalosos</strong>: usa calzado antideslizante, mantente lejos del borde y nunca te lances` } as T, { zh: `潭水深约 6 米，<strong>无救生员</strong>，请看护好儿童，量力戏水`, en: `The pool is ~6 m deep with <strong>no lifeguard</strong> — supervise children and swim within your limits`, it: `La pozza è profonda circa 6 m e <strong>non c'è bagnino</strong>: sorveglia i bambini e nuota nei tuoi limiti`, es: `La poza tiene unos 6 m de profundidad y <strong>no hay guardavidas</strong>: vigila a los niños y bana dentro de tus límites` } as T, { zh: `周边<strong>无任何设施</strong>（无厕所、无饮水、无小卖部），请自备饮水与食物`, en: `There are <strong>no facilities nearby</strong> (no toilet, water or kiosk) — bring your own`, it: `Non ci sono <strong>servizi vicino</strong> (né bagno, né acqua, né chiosco): porta i tuoi`, es: `No hay <strong>servicios cercanos</strong> (ni baño, ni agua, ni kiosco): traiga lo suyo` } as T, { zh: `<strong>无垃圾桶</strong>，请带走所有垃圾，践行“无痕山林”`, en: `<strong>No bins</strong> — carry out all litter and practise Leave No Trace`, it: `<strong>Non ci sono cestini</strong>: porta via i rifiuti e pratica Non Lasciare Traccia`, es: `<strong>No hay tachos</strong>: lleve su basura y practique No Dejar Rastro` } as T, { zh: `步道位于<strong>步行小镇</strong>内，车辆需停在镇外停车场，再步行进入`, en: `The trail lies inside a <strong>pedestrian town</strong> — park outside and walk in`, it: `Il sentiero è dentro un <strong>paese pedonale</strong>: parcheggia fuori e cammina`, es: `El sendero está dentro de un <strong>pueblo peatonal</strong>: estacione afuera y camine` } as T,
    { zh: `步道及水潭<strong>无移动信号</strong>，请在镇中心加载地图并向家人报备行程`, en: `The trail and pool have <strong>no mobile signal</strong> — load your map in town and tell someone your plan`, it: `Sentiero e pozza <strong>senza segnale</strong>: carica la mappa in paese e avvisa i tuoi`, es: `El sendero y la poza <strong>no tienen señal</strong>: carga el mapa en el pueblo y avisa a tu familia` } as T,
    { zh: `步道含土路与石阶，<strong>不适合轮椅与婴儿推车</strong>；婴儿建议用背带`, en: `The trail has dirt and stone steps — <strong>not for wheelchairs or strollers</strong>; use a baby carrier`, it: `Sentiero con terra e scalini: <strong>non per carrozzine</strong>; usa un marsupio`, es: `Sendero con tierra y escalones: <strong>no apto para sillas ni coches</strong>; usa un portabebés` } as T] },
  ],
};

// ── Transport ──
export const transport = {
  sectionNum: { zh: `交通指南`, en: `Transport`, it: `Trasporti`, es: `Transporte` } as T,
  heading: { zh: `五种方式<br/><em class="text-[color:var(--color-emerald)]">到达水潭</em>`, en: `Five ways<br/><em class="text-[color:var(--color-emerald)]">to arrive</em>`, it: `Cinque modi<br/><em class="text-[color:var(--color-emerald)]">di arrivare</em>`, es: `Cinco formas<br/><em class="text-[color:var(--color-emerald)]">de llegar</em>` } as T,
  subtitle: { zh: `La Olla 位于科尔多瓦省卡拉穆奇塔山谷的拉昆布雷西塔镇旁，距省会科尔多瓦市约 130 公里。从市区自驾通常约 2 小时；抵达后需将车辆停在镇外，步行进入这座没有汽车的步行小镇，再沿标识步道前往水潭。`, en: `La Olla sits beside La Cumbrecita in the Calamuchita Valley of Córdoba, about 130 km from the provincial capital Córdoba. From the city it is usually a 2-hour drive; on arrival you park outside the car-free pedestrian town and walk in, then follow the signed trail to the pool.`, it: `La Olla si trova accanto a La Cumbrecita nella valle di Calamuchita, a Córdoba, a circa 130 km dal capoluogo Córdoba. Dalla città si arriva di solito in 2 ore; all'arrivo si parcheggia fuori dal paese pedonale e si entra a piedi, poi si segue il sentiero segnalato fino alla pozza.`, es: `La Olla está junto a La Cumbrecita en el Valle de Calamuchita, Córdoba, a unos 130 km de la capital provincial Córdoba. Desde la ciudad suele ser un trayecto de 2 horas; al llegar se estaciona fuera del pueblo peatonal y se entra a pie, luego se sigue el sendero señalizado hasta la poza.` } as T,
  items: [
    { icon: '🚗', title: { zh: `自驾 / 摩托车`, en: `By car or motorbike`, it: `In auto o moto`, es: `En auto o moto` } as T, meta: { zh: `约 130 公里 · 2 小时`, en: `~130 km · 2 h`, it: `~130 km · 2 h`, es: `~130 km · 2 h` } as T, details: [{ icon: '🛣️', text: { zh: `从科尔多瓦市沿 RN36 向南，转至卡拉穆奇塔山谷方向，经 Villa General Belgrano 抵达拉昆布雷西塔镇外停车场。最后一段为步行，镇内禁止机动车通行。`, en: `From Córdoba city take RN36 south toward the Calamuchita Valley, via Villa General Belgrano, to the parking lot outside La Cumbrecita. The final stretch is on foot — cars are banned in the town.`, it: `Da Córdoba prendi la RN36 a sud verso la valle di Calamuchita, passando per Villa General Belgrano, fino al parcheggio fuori La Cumbrecita. L'ultimo tratto è a piedi: le auto sono vietate nel paese.`, es: `Desde Córdoba toma la RN36 al sur hacia el Valle de Calamuchita, vía Villa General Belgrano, hasta el estacionamiento fuera de La Cumbrecita. El último tramo es a pie: los autos están prohibidos en el pueblo.` } as T }, { icon: '🅿️', text: { zh: `周末与旺季镇外停车场易满，建议早到；停车后沿主街步行约 15–20 分钟接上通往 La Olla 的步道。`, en: `The parking lot outside town fills up on weekends and in high season — arrive early; after parking, walk the main street ~15–20 min to join the La Olla trail.`, it: `Il parcheggio fuori dal paese si riempie nei weekend e in alta stagione: arriva presto; dopo il parcheggio, cammina la via principale ~15–20 min fino al sentiero di La Olla.`, es: `El estacionamiento fuera del pueblo se llena los fines de semana y en temporada alta: llega temprano; tras estacionar, camina la calle principal ~15–20 min hasta el sendero de La Olla.` } as T }] },
    { icon: 'Air', title: { zh: `从科尔多瓦机场出发`, en: `From Córdoba airport`, it: `Dall'aeroporto di Córdoba`, es: `Desde el aeropuerto de Córdoba` } as T, meta: { zh: `落地后接驳`, en: `After-landing transfer`, it: `Trasferimento dall'aeroporto`, es: `Traslado tras el aterrizaje` } as T, details: [{ icon: 'Bag', text: { zh: `科尔多瓦国际机场（Pajas Blancas, COR）位于市区西北；落地后最省心的方式通常是租车、remis 或 taxi，直接前往拉昆布雷西塔，再将车停在镇外。`, en: `Córdoba International Airport (Pajas Blancas, COR) lies northwest of the city; after landing, the easiest option is usually a rental car, remis or taxi straight to La Cumbrecita, parking outside the town.`, it: `L'aeroporto internazionale di Córdoba (Pajas Blancas, COR) è a nord-ovest della città; dopo l'atterraggio, l'opzione più semplice è solitamente un'auto a noleggio, un remis o un taxi diretto a La Cumbrecita, parcheggiando fuori dal paese.`, es: `El Aeropuerto Internacional de Córdoba (Pajas Blancas, COR) está al noroeste de la ciudad; al aterrizar, lo más práctico suele ser alquilar un auto, o tomar un remis o taxi directo a La Cumbrecita, estacionando fuera del pueblo.` } as T }, { icon: 'Transfer', text: { zh: `若预算有限：落地后先乘坐 AEROBUS 机场大巴或出租车前往“科尔多瓦长途汽车站（Terminal de Ómnibus de Córdoba）”。在那里搭乘 Buses Lep 或 Sierras de Calamuchita 等长途客运公司的班车，通常经停 Villa General Belgrano，最终抵达拉昆布雷西塔镇入口，再步行进入水潭步道。`, en: `If you are on a budget: after landing, take the AEROBUS airport shuttle or a taxi to the "Córdoba Bus Terminal (Terminal de Ómnibus de Córdoba)". There, board a long-distance service such as Buses Lep or Sierras de Calamuchita; it usually stops at Villa General Belgrano and finally reaches the entrance of La Cumbrecita, from where you walk to the pool trail.`, it: `Se vuoi spendere meno: dopo l'atterraggio, prendi la navetta aeroportuale AEROBUS o un taxi verso la "Terminal de Ómnibus de Córdoba". Lì sali su un servizio a lunga percorrenza come Buses Lep o Sierras de Calamuchita; di solito ferma a Villa General Belgrano e arriva infine all'ingresso di La Cumbrecita, da cui si cammina al sentiero della pozza.`, es: `Si busca ahorrar: tras aterrizar, tome la naveta del aeropuerto AEROBUS o un taxi hasta la "Terminal de Ómnibus de Córdoba". Allí aborde un servicio de larga distancia como Buses Lep o Sierras de Calamuchita; suele parar en Villa General Belgrano y llega finalmente a la entrada de La Cumbrecita, desde donde se camina al sendero de la poza.` } as T }] },
    { icon: 'Cab', title: { zh: `出租车 / Remis / 网约接送`, en: `Taxi / remis / private ride`, it: `Taxi / remis / auto privata`, es: `Taxi / remis / traslado privado` } as T, meta: { zh: `点对点省心`, en: `Easy door to door`, it: `Comodo porta a porta`, es: `Comodidad puerta a puerta` } as T, details: [{ icon: 'Hotel', text: { zh: `适合不想自驾、又不愿等公交的旅客；可从科尔多瓦市区或机场直接叫车前往拉昆布雷西塔，尤其适合携带行李、戏水装备或同行长者时。`, en: `Ideal if you do not want to drive but also do not want to wait for the bus; book a direct ride from Córdoba city or the airport, especially handy with luggage, swim gear or older companions.`, it: `Ideale se non vuoi guidare ma nemmeno aspettare l'autobus; prenota un tragitto diretto da Córdoba o dall'aeroporto, comodo con bagagli, attrezzatura da bagno o persone anziane.`, es: `Ideal si no quiere conducir pero tampoco esperar el colectivo; reserve un viaje directo desde Córdoba o el aeropuerto, especialmente útil con equipaje, artículos de baño o personas mayores.` } as T }, { icon: 'Call', text: { zh: `返程车在淡季较少，最好提前确认司机是否等候或安排好回程叫车方式。`, en: `Return rides can be harder to find in the low season, so confirm in advance whether the driver will wait or help arrange the ride back.`, it: `In bassa stagione i ritorni sono più rari, quindi verifica in anticipo se l'autista aspetta o aiuta a organizzare il rientro.`, es: `En temporada baja los retornos son más escasos, así que confirme antes si el chofer espera o ayuda a organizar la vuelta.` } as T }] },
    { icon: 'Bus', title: { zh: `公共交通 · 山谷班车`, en: `Public bus · Valley service`, it: `Trasporto pubblico · servizio di valle`, es: `Transporte público · servicio de valle` } as T, meta: { zh: `经 Villa General Belgrano`, en: `Via Villa General Belgrano`, it: `Via Villa General Belgrano`, es: `Vía Villa General Belgrano` } as T, details: [{ icon: 'Fare', text: { zh: `从科尔多瓦市搭乘前往卡拉穆奇塔山谷（经 Villa General Belgrano、Santa Rosa de Calamuchita）的班车，在拉昆布雷西塔下车后步行进入小镇与步道。票价便宜，对无车背包客非常友好。`, en: `From Córdoba take a valley service toward Calamuchita (via Villa General Belgrano, Santa Rosa de Calamuchita); get off at La Cumbrecita and walk into the town and onto the trail. Cheap and friendly to car-free travellers.`, it: `Da Córdoba prendi un servizio di valle verso Calamuchita (via Villa General Belgrano, Santa Rosa de Calamuchita); scendi a La Cumbrecita e cammina nel paese e sul sentiero. Economico e ottimo per chi viaggia senza auto.`, es: `Desde Córdoba tome un servicio de valle hacia Calamuchita (vía Villa General Belgrano, Santa Rosa de Calamuchita); baje en La Cumbrecita y camine hacia el pueblo y el sendero. Económico y muy amigable para quienes no tienen auto.` } as T }, { icon: 'Transfer', text: { zh: `班次有限，建议提前查好当日时刻表；下车后务必留意末班车时间，预留步行与等车余量。`, en: `Services are limited — check the same-day timetable in advance; after alighting, always note the last return bus and allow walking and waiting time.`, it: `Le corse sono limitate: controlla in anticipo l'orario del giorno; dopo essere sceso, annotati l'ultimo bus di ritorno e lascia margine per camminare e aspettare.`, es: `Los servicios son limitados: revise con antelación el horario del día; tras bajar, anote el último colectivo de regreso y deje margen para caminar y esperar.` } as T }] },
    { icon: '🚶', title: { zh: `步行 / 徒步`, en: `On foot`, it: `A piedi`, es: `A pie` } as T, meta: { zh: `镇内禁行机动车`, en: `Car-free town`, it: `Paese senza auto`, es: `Pueblo sin autos` } as T, details: [{ icon: '', text: { zh: `拉昆布雷西塔是一座没有汽车的步行小镇。车辆停在镇外停车场后，沿主街与清晰标识的步道步行约 1–2 小时即可抵达 La Olla，沿途溪水与山林相伴，本身就是一段治愈的旅程。`, en: `La Cumbrecita is a car-free pedestrian town. After parking outside, follow the main street and the clearly signed trail for about 1–2 hours to La Olla; the stream and forest along the way make the walk a soothing journey in itself.`, it: `La Cumbrecita è un paese pedonale senza auto. Dopo aver parcheggiato fuori, segui la via principale e il sentiero ben segnalato per circa 1–2 ore fino a La Olla; il ruscello e il bosco lungo il percorso rendono la camminata un viaggio rigenerante.`, es: `La Cumbrecita es un pueblo peatonal sin autos. Tras estacionar afuera, sigue la calle principal y el sendero bien señalizado unas 1–2 horas hasta La Olla; el arroyo y el bosque durante el recorrido convierten la caminata en un viaje relajante.` } as T }] },
  ],
};

// ── Climate & Light ──
export const climate = {
  sectionNum: { zh: `气候与光影`, en: `Climate & Light`, it: `Clima e luce`, es: `Clima y Luz` } as T,
  heading: { zh: `此刻，山谷的<br/><em class="text-[color:var(--color-emerald)]">风与水</em>`, en: `Today's live rhythm<br/><em class="text-[color:var(--color-emerald)]"> of wind & water</em>`, it: `Il ritmo in diretta<br/><em class="text-[color:var(--color-emerald)]">di vento e acqua</em>`, es: `El ritmo en vivo<br/><em class="text-[color:var(--color-emerald)]"> del viento y el agua</em>` } as T,
  subtitle: { zh: `卡拉穆奇塔山谷以“四季分明、午后易阵雨”著称。以下数据由公开 API（Open-Meteo）实时获取，供您规划行程与拍摄。`, en: `Calamuchita is known for distinct seasons and afternoon showers. Data below is fetched live from the public Open-Meteo API to help you plan and shoot.`, it: `Calamuchita è famosa per stagioni nette e rovesci pomeridiani. I dati sotto arrivano in tempo reale dall'API pubblica Open-Meteo per aiutarti a pianificare e fotografare.`, es: `Calamuchita es conocida por estaciones marcadas y chaparrones por la tarde. Los datos se obtienen en vivo de la API pública de Open-Meteo para ayudarle a planificar y fotografiar.` } as T,
  windLabel: { zh: `当前风速`, en: `Current wind`, it: `Vento attuale`, es: `Viento actual` } as T,
  directionLabel: { zh: `风向`, en: `Wind direction`, it: `Direzione del vento`, es: `Dirección del viento` } as T,
  gustLabel: { zh: `阵风`, en: `Gusts`, it: `Raffiche`, es: `Ráfagas` } as T,
  sunsetLabel: { zh: `今日日落`, en: `Today's sunset`, it: `Tramonto oggi`, es: `Puesta de sol hoy` } as T,
  goldenHourLabel: { zh: `黄金时刻`, en: `Golden Hour`, it: `Ora dorata`, es: `Hora Dorada` } as T,
  goldenHourDesc: { zh: `日落前约 60 分钟，岩壁被夕阳染成暖金，是摄影的黄金窗口。`, en: `About 60 minutes before sunset the rock glows warm gold — the golden window for photography.`, it: `Circa 60 minuti prima del tramonto la roccia splende d'oro caldo — la finestra dorata per la fotografia.`, es: `Unos 60 minutos antes de la puesta, la roca se tiñe de oro cálido: la ventana dorada para la fotografía.` } as T,
  timelineLabel: { zh: `光线时间轴`, en: `Light timeline`, it: `Linea temporale della luce`, es: `Línea de tiempo de la luz` } as T,
  timelineDesc: { zh: `拖动时间，直观感受“黄金时刻”为何在日落前后最盛。此为示意曲线（以日照角度近似），请以现场观感与官方数据为准。`, en: `Drag the time to feel why the Golden Hour peaks around sunset. This is an illustrative curve (sun-angle approximation), not a measurement.`, it: `Trascina l'ora per percepire perché l'Ora dorata raggiunge il picco vicino al tramonto. Curva illustrativa (approssimazione dell'angolo solare), non una misurazione.`, es: `Arrastre la hora para ver por qué la Hora Dorada alcanza su punto máximo cerca del atardecer. Es una curva ilustrativa (aprox. del ángulo solar), no una medición.` } as T,
  timelineTime: { zh: `时间`, en: `Time`, it: `Ora`, es: `Hora` } as T,
  timelineGlow: { zh: `金色强度`, en: `Golden glow`, it: `Intensità dorata`, es: `Intensidad dorada` } as T,
  timelineBest: { zh: `推荐窗口：日落前 60 分钟`, en: `Best window: 60 min before sunset`, it: `Migliore finestra: 60 min prima del tramonto`, es: `Mejor ventana: 60 min antes del atardecer` } as T,
  loading: { zh: `正在获取实时数据…`, en: `Loading live data…`, it: `Caricamento dati in tempo reale…`, es: `Cargando datos en vivo…` } as T,
  error: { zh: `实时数据暂时不可用，请参考上方游览指南。`, en: `Live data unavailable — see the guide above.`, it: `Dati in tempo reale non disponibili — vedi la guida sopra.`, es: `Datos en vivo no disponibles — consulte la guía superior.` } as T,
  source: { zh: `数据来源：Open-Meteo`, en: `Source: Open-Meteo`, it: `Fonte: Open-Meteo`, es: `Fuente: Open-Meteo` } as T,
};

// ── Gallery ──
export const gallery = {
  sectionNum: { zh: `视觉图集`, en: `Gallery`, it: `Galleria`, es: `Galería` } as T,
  heading: { zh: `水、岩、林、光`, en: `Water. Rock. Forest. Light.`, it: `Acqua. Roccia. Bosco. Luce.`, es: `Agua. Roca. Bosque. Luz.` } as T,
  photoLabel: { zh: `照片`, en: `Photo`, it: `Foto`, es: `Foto` } as T,
  viewMorePhotos: { zh: `在 Google 地图上查看更多照片`, en: `View more photos on Google Maps`, it: `Vedi più foto su Google Maps`, es: `Ver más fotos en Google Maps` } as T,
};

// ── Reviews ──
export const reviews = {
  sectionNum: { zh: `游客评价`, en: `Reviews`, it: `Recensioni`, es: `Opiniones` } as T,
  heading: { zh: `4.7<span class="text-[color:var(--color-emerald)]">/5</span> · 来自 19,312 位旅行者`, en: `4.7<span class="text-[color:var(--color-emerald)]">/5</span> · from 19,312 travelers`, it: `4.7<span class="text-[color:var(--color-emerald)]">/5</span> · di oltre 19.312 viaggiatori`, es: `4.7<span class="text-[color:var(--color-emerald)]">/5</span> · de más de 19.312 viajeros` } as T,
  viewMoreReviews: { zh: `在 Google 地图上查看更多评价`, en: `View more reviews on Google Maps`, it: `Vedi più recensioni su Google Maps`, es: `Ver más opiniones en Google Maps` } as T,
  items: [
    { stars: '★★★★★', date: '2026-05', title: { zh: `"清凉又治愈的天然泳池"`, en: `"Cool and healing"`, it: `"Fresca e rigenerante"`, es: `"Fresca y relajante"` } as T, desc: { zh: `没想到步行小镇旁藏着这么一口碧绿的水潭。夏季跳进去凉到骨子里，瀑布声在岩壁间回荡，值回整段徒步。`, en: `Didn't expect such an emerald pool next to a pedestrian town. In summer the plunge is bracingly cold and the falls echo off the rock — worth the whole hike.`, it: `Non mi aspettavo una pozza così verde accanto a un paese pedonale. D'estate il tuffo è freschissimo e la cascata rimbomba sulla roccia: vale tutta la camminata.`, es: `No esperaba una poza tan verde junto a un pueblo peatonal. En verano el salto es fresquísimo y la cascada retumba en la roca: vale toda la caminata.` } as T, author: 'Lucía M. · 🇦🇷' },
    { stars: '★★★★★', date: '2026-03', title: { zh: `"家庭戏水首选"`, en: `"Family favourite"`, it: `"Preferita in famiglia"`, es: `"Favorita en familia"` } as T, desc: { zh: `带娃从拉昆布雷西塔步行过来，步道清晰好走。孩子在潭边玩水开心得不得了，就是岩石湿滑要盯紧。`, en: `Walked over from La Cumbrecita with the kids — the trail is clear and easy. They loved playing in the pool; just keep a close eye, the rock is slippery.`, it: `Siamo venuti a piedi da La Cumbrecita con i bambini: il sentiero è chiaro e facile. Si sono divertiti un mondo nella pozza; solo, occhio, la roccia è scivolosa.`, es: `Vinimos caminando desde La Cumbrecita con los chicos: el sendero es claro y fácil. Se divirtieron mucho en la poza; solo, ojo, la roca está resbalosa.` } as T, author: 'Tomás R. · 🇦🇷' },
    { stars: '★★★★★', date: '2025-11', title: { zh: `"雨后瀑布最壮观"`, en: `"Best after rain"`, it: `"Spettacolare dopo la pioggia"`, es: `"Espectacular tras la lluvia"` } as T, desc: { zh: `选在阵雨后来，水量大得惊人，壶穴被冲得轰隆作响。照片怎么拍都好看，是卡拉穆奇塔的隐藏宝藏。`, en: `Came just after a shower — the flow was astonishing and the pothole roared. Photos look great from every angle; a hidden gem of Calamuchita.`, it: `Venuti subito dopo un rovescio: la portata era sorprendente e la marmitta ruggiva. Foto belle da ogni angolo: un gioiello nascosto di Calamuchita.`, es: `Vinimos justo tras una lluvia: el caudal era asombroso y la marmita rugía. Fotos lindas desde cualquier ángulo: una joya oculta de Calamuchita.` } as T, author: 'Wang Y. · 🇨🇳' },
    { stars: '★★★★<span class="text-black/20">★</span>', date: '2025-09', title: { zh: `"岩石真的滑"`, en: `"The rock is slippery"`, it: `"La roccia è scivolosa"`, es: `"La roca está resbalosa"` } as T, desc: { zh: `风景满分，但潭边岩石比我想象中滑很多，差点摔倒。建议穿溯溪鞋，别在边缘逗留。`, en: `Views are perfect, but the rock by the pool was far slippier than I expected — nearly fell. Wear water shoes and don't linger at the edge.`, it: `Le viste sono perfette, ma la roccia accanto alla pozza è molto più scivolosa del previsto: ho rischiato di cadere. Usa scarpe da acqua e non trattenarti sul bordo.`, es: `Las vistas son perfectas, pero la roca junto a la poza está mucho más resbalosa de lo que pensaba: casi me caigo. Usa calzado de agua y no te demores en el borde.` } as T, author: 'James W. · 🇺🇸' },
    { stars: '★★★★★', date: '2025-08', title: { zh: `"背包客友好"`, en: `'Backpacker friendly'`, it: `'Ottimo per zaino in spalla'`, es: `'Amigable para mochileros'` } as T, desc: { zh: `没车也能来！坐山谷班车到拉昆布雷西塔，下车步行进镇再走步道。车票便宜，小镇安静得像世外桃源。`, en: `Came without a car! Took the valley bus to La Cumbrecita, walked into town and on to the trail. Cheap fare and the town is as peaceful as a hideaway.`, it: `Senza auto ci sono riuscito! Ho preso il bus di valle fino a La Cumbrecita, sono entrato a piedi e ho proseguito sul sentiero. Economico e il paese è tranquillo come un rifugio.`, es: `¡Vine sin auto! Tomé el bus de valle hasta La Cumbrecita, caminé al pueblo y seguí el sendero. Económico y el pueblo es tranquilo como un refugio.` } as T, author: 'Sofía P. · 🎒' },
    { stars: '★★★★★', date: '2025-06', title: { zh: `"清晨的绿光"`, en: `The morning green`, it: `Il verde del mattino`, es: `El verde de la mañana` } as T, desc: { zh: `专门赶早到，薄雾还没散，水面静得像一块翡翠。是我这趟科尔多瓦最难忘的十分钟。`, en: `Arrived early on purpose — mist still hanging, the surface still as a jade stone. The most unforgettable ten minutes of the trip.`, it: `Arrivato apposta presto: la nebbia ancora sospesa, la superficie ferma come una pietra di giada. I dieci minuti più indimenticabili del viaggio.`, es: `Llegué temprano a propósito: la neblina aún suspendida, la superficie quieta como una piedra de jade. Los 10 minutos más inolvidables del viaje.` } as T, author: 'Marina C. · 📷' },
    { stars: '★★★★<span class="text-black/20">★</span>', date: '2025-04', title: { zh: `"旺季人不少"`, en: `"Busy in season"`, it: `"Affollato in alta stagione"`, es: `"Concurrido en temporada"` } as T, desc: { zh: `夏季周末人挺多的，潭边有点挤。建议工作日或一早来，体验会好很多。`, en: `Summer weekends get crowded and the pool edge fills up. A weekday or an early arrival makes a big difference.`, it: `I weekend d'estate si riempie e il bordo della pozza è affollato. Un giorno feriale o un arrivo presto cambia molto.`, es: `Los fines de semana de verano se llena y el borde de la poza se congestiona. Un día de diario o llegar temprano cambia mucho.` } as T, author: 'Nuno P. · 🇧🇷' },
    { stars: '★★★★★', date: '2025-02', title: { zh: `"没有商业味"`, en: `"No commercial feel"`, it: `"Senza aria commerciale"`, es: `"Sin olor a negocio"` } as T, desc: { zh: `没有售票亭、没有小卖部，只有水和岩。这种“纯天然”的水潭反而最让人放松，请一起保持它的干净。`, en: `No booth, no kiosk — just water and rock. This "purely natural" pool is the most relaxing exactly because of that. Let's keep it clean together.`, it: `Nessun chiosco, nessuna biglietteria: solo acqua e roccia. Questa pozza "puramente naturale" rilassa proprio per questo. Custodiamola pulita insieme.`, es: `Sin boletería ni kiosco: solo agua y roca. Esta poza "puramente natural" relaja justo por eso. Cuidémosla limpia entre todos.` } as T, author: 'Aya K. · 🌿' },
  ],
};

// ── Surrounding ──
export const surrounding = {
  sectionNum: { zh: `周边联动`, en: `Nearby`, it: `Dintorni`, es: `Alrededores` } as T,
  heading: { zh: `还可以<em class="text-[color:var(--color-emerald)]">连着玩</em>`, en: `Extend the trip<br/><em class="text-[color:var(--color-emerald)]"> further</em>`, it: `Estendi il viaggio<br/><em class="text-[color:var(--color-emerald)]">ancora oltre</em>`, es: `Extienda el viaje<br/><em class="text-[color:var(--color-emerald)]"> aún más</em>` } as T,
  items: [
    { img: '/gallery/la-olla-10.jpg', title: { zh: `🚶 拉昆布雷西塔步行小镇`, en: `🚶 La Cumbrecita pedestrian town`, it: `🚶 La Cumbrecita, paese pedonale`, es: `🚶 La Cumbrecita, pueblo peatonal` } as T, desc: { zh: `没有汽车的阿尔卑斯风情小镇，主街以花岗岩铺就，溪水穿镇而过。镇内餐厅、旅舍与手作小店一应俱全，是前往 La Olla 的起点与补给站。`, en: `An Alpine-style car-free town with granite-paved streets and a stream running through it. Restaurants, lodges and craft shops line the centre — the starting point and base for La Olla.`, it: `Un paese alpino senza auto, con vie lastricate di granito e un ruscello che lo attraversa. Ristoranti, lodge e botteghe artigiane nel centro: il punto di partenza per La Olla.`, es: `Un pueblo alpino sin autos, con calles empedradas de granito y un arroyo que lo cruza. Restaurantes, hosterías y artesanías en el centro: el punto de partida para La Olla.` } as T },
    { img: '/gallery/la-olla-11.jpg', title: { zh: `🌄 卡拉穆奇塔山谷`, en: `🌄 Calamuchita Valley`, it: `🌄 Valle di Calamuchita`, es: `🌄 Valle de Calamuchita` } as T, desc: { zh: `科尔多瓦南部的生态旅游心脏，连绵的 Sierra 丘陵、溪流与德裔移民小镇交织。自驾或骑行穿行其间，处处是清新的山野气息。`, en: `The ecotourism heart of southern Córdoba, where rolling Sierras, streams and German-immigrant towns intertwine. Drive or cycle through it for fresh mountain air at every turn.`, it: `Il cuore ecoturistico della Córdoba meridionale, dove si intrecciano Sierras, ruscelli e paesi di immigrati tedeschi. In auto o in bici, aria di montagna a ogni curva.`, es: `El corazón ecoturístico del sur de Córdoba, donde se entrelazan Sierras, arroyos y pueblos de inmigrantes alemanes. En auto o bici, aire de montaña en cada curva.` } as T },
    { img: '/gallery/la-olla-12.jpg', title: { zh: `🍺 Villa General Belgrano`, en: `🍺 Villa General Belgrano`, it: `🍺 Villa General Belgrano`, es: `🍺 Villa General Belgrano` } as T, desc: { zh: `以啤酒节（Oktoberfest）闻名的德裔小镇，距拉昆布雷西塔约 20 分钟车程。可顺路品尝自酿啤酒、德式香肠与黑森林蛋糕。`, en: `A German-heritage town famous for its Oktoberfest, about 20 minutes from La Cumbrecita. Worth a stop for craft beer, sausages and Black Forest cake.`, it: `Paese di origine tedesca famoso per l'Oktoberfest, a circa 20 minuti da La Cumbrecita. Merita una sosta per birra artigianale, salsicce e torta della Foresta Nera.`, es: `Pueblo de herencia alemana famoso por su Oktoberfest, a unos 20 minutos de La Cumbrecita. Vale una parada por cerveza artesanal, salchichas y pastel de la Selva Negra.` } as T },
    { img: '/gallery/la-olla-13.jpg', title: { zh: `⛰️ 钦帕基山（Cerro Champaquí）`, en: `⛰️ Cerro Champaquí`, it: `⛰️ Cerro Champaquí`, es: `⛰️ Cerro Champaquí` } as T, desc: { zh: `科尔多瓦山脉的最高峰（约 2,884 米），登顶可俯瞰整片卡拉穆奇塔山谷。适合有经验的徒步者作为 La Olla 之后的进阶行程。`, en: `The highest peak of the Córdoba Sierras (~2,884 m); the summit overlooks the whole Calamuchita Valley. A good advanced hike for experienced walkers after La Olla.`, it: `La vetta più alta delle Sierras di Córdoba (~2.884 m); dalla cima si vede tutto il Valle di Calamuchita. Ottima escursione avanzata dopo La Olla.`, es: `La cumbre más alta de las Sierras de Córdoba (~2.884 m); desde la cima se ve todo el Valle de Calamuchita. Buen trek avanzado tras La Olla.` } as T },
    { img: '/gallery/la-olla-14.jpg', title: { zh: `💦 阿尔姆巴赫溪（Arroyo Almbach）`, en: `💦 Arroyo Almbach`, it: `💦 Arroyo Almbach`, es: `💦 Arroyo Almbach` } as T, desc: { zh: `雕琢 La Olla 与拉昆布雷西塔的，是阿尔姆巴赫溪（Arroyo Almbach）与附近的中河（Río del Medio）。溪流自科尔多瓦山脉汇流而下，冲刷出这口碧潭，并在镇中穿行。亚坎托河（Río Yacanto）位于山谷另一侧，与此景点无关。`, en: `What carved La Olla and La Cumbrecita is Arroyo Almbach, together with the nearby Río del Medio. The streams gather from the Córdoba Sierras and cut this green pool, also running through the town. The Río Yacanto lies on the other side of the valley and is unrelated to this site.`, it: `Ciò che ha scolpito La Olla e La Cumbrecita è l'Arroyo Almbach, insieme al vicino Río del Medio. I ruscelli scendono dalle Sierras de Córdoba e intagliano questa pozza, attraversando anche il paese. Il Río Yacanto si trova dall'altra parte della valle e non ha a che fare con questo luogo.`, es: `Lo que talló La Olla y La Cumbrecita es el Arroyo Almbach, junto con el cercano Río del Medio. Los arroyos bajan de las Sierras de Córdoba y esculpen esta poza, atravesando también el pueblo. El Río Yacanto queda del otro lado del valle y no tiene relación con este sitio.` } as T },
  ],
};
